[WIP]開発環境と本番環境でアプリを分ける
HaraFuchi/RandomChoiceApp pull request #114
Opened 2021-01-01 19:44 UTC by fuchi0741

## clone コマンド
git clone git@github.com:HaraFuchi/RandomChoiceApp.git -b ブランチ名

## Trello
該当のTrelloのチケットの名称を共有

## 概要
このPRの概要

## レビューで見て欲しいポイント

## 参考URL

## 実機build/期待通りの挙動をするか
OK

## レビュー依頼
※自分の名前を消してください  
※ふちとあやののレビューが完了したらやまたくさんにレビューを投げる  
※[WIP]の場合は全て消して依頼しないようにしてください  
@fuchi0741  

レビューお願いしますー！
 
## 補足

2021-01-02 09:16 UTC, AyanoHara requested changes
@fuchi0741 
DebugさいころdeごはんのSchemeが表示されません💦
確認お願いします！

<img width="406" alt="スクリーンショット 2021-01-02 18 07 10" src="https://user-images.githubusercontent.com/65425673/103454364-80353a00-4d26-11eb-998d-b10764a7e3ff.png">

2021-01-02 17:00 UTC, fuchi0741 commented
@AyanoHara 指摘事項修正しました！
ご確認お願いしますー！

2021-01-07 16:20 UTC, AyanoHara reviewed
@fuchi0741 
Debugさいころdeごはんビルドできました！！

一点だけ確認しておきたい箇所をコメントします！
Debugさいころdeごはんをビルドした際、下記のログがコンソールに表示されるのが気になります。

<img width="630" alt="スクリーンショット 2021-01-07 15 48 29" src="https://user-images.githubusercontent.com/65425673/103916155-6ee99480-514f-11eb-9719-039ea3003be1.png">


恐らくこれはDebug用のSchemeを作成したことにより、元々Firebaseに登録していたBundleIDと異なるものが使用されているためだと思うのですが、、、
個人的には今後Firebaseの方も本番環境とDebug環境を分ける予定ですし、今のところ問題なくFirebaseと連携できているので、もし他に考えられる影響がないのなら一旦スルーしてこのPRをマージしたのち別途対応（Firebaseを本番環境とDebug環境で分ける）でもよいかなと考えているのですが、どうでしょうか？

確認お願いします🙇‍♀️

2021-01-07 17:11 UTC, fuchi0741 commented
@AyanoHara 
ナイス指摘です！
後ほどFIrebaseを環境ごとに分けるので一旦スルーでいいかと思います！

2021-01-12 14:03 UTC, fuchi0741 commented
@yamataku29 @AyanoHara 
お時間のあるタイミングにレビューお願い致します！

2021-01-12 14:26 UTC, AyanoHara commented
> ナイス指摘です！
> 後ほどFIrebaseを環境ごとに分けるので一旦スルーでいいかと思います！
@fuchi0741 
了解しましたー！

2021-01-12 14:27 UTC, AyanoHara approved these changes
@fuchi0741 
良いと思います！LGTM！

2021-01-13 01:12 UTC, yamataku29 reviewed
1点だけコメントしました💁‍♂️💡

2021-01-13 01:12 UTC, yamataku29 commented on RandomChoiceApp/Controller/AppDelegate.swift
> +            print("⚠️⚠️⚠️本番環境⚠️⚠️⚠️")
本番環境ではログを出力してもあまり恩恵は無いので、これは無くても良さそうですね💁‍♂️

2021-01-13 04:38 UTC, fuchi0741 commented on RandomChoiceApp/Controller/AppDelegate.swift
> +            print("⚠️⚠️⚠️本番環境⚠️⚠️⚠️")
@yamataku29 
↑削除しました！
引き続きレビューお願い致します！

2021-01-13 06:36 UTC, yamataku29 approved these changes
LGTM!🙆‍♂️🎉

2021-01-13 07:02 UTC, fuchi0741 commented
@AyanoHara マージします！

2021-01-13 07:02 UTC, merged