さいころタップでnilが返った場合のアラート / 一部アラートのリファクタリング
HaraFuchi/RandomChoiceApp pull request #45
Opened 2020-08-28 12:40 UTC by fuchi0741

## clone コマンド
git clone -b feature/fix-dice-button git@github.com:HaraFuchi/RandomChoiceApp.git

## Trello
起動直後にサイコロを押すとnilが帰ってくるので/ボタンを押せなくする

## 概要
さいころタップでnilが返っ

1. た場合のアラートを出す
2. 一部アラートのリファクタリング

## レビューで見て欲しいポイント
アラートが意図されたタイミングで表示されるか？

## 実機build/期待通りの挙動をするか
OK

## 追加したチケット
アプリ起動直後にさいころを押した倍にnilがくるハンドリングをアラートではなく、さいころのプロパティを変えて実現する

2020-08-28 17:38 UTC, AyanoHara requested changes
@fuchi0741 
修正お願いします！！

2020-08-28 17:38 UTC, AyanoHara commented on RandomChoiceApp/Controller/RandomChoiceViewController.swift
> +    }
お店の登録状況がアリの場合の挙動は問題なし。登録がゼロだった場合「サイコロをもう一度振ってください」のアラートが出続けてしまうので修正お願いします！

2020-09-22 06:58 UTC, fuchi0741 commented
@AyanoHara (cc @yamataku29)
nilを回避する方法が決まったので、このPRはクローズします

2020-09-22 06:59 UTC, closed without merging

2020-09-22 07:05 UTC, yamataku29 commented on RandomChoiceApp/Controller/RandomChoiceViewController.swift
> +        if storeDataArray.isEmpty == true {
ここの`== true`は省略可能なので、書かない方がよいですね💁‍♂️
Swiftでは、真偽値が自明な場合はイコールオペレーターを省略するのが慣習なので、その様にリファクタリングするとよいでしょう。

```swift
if storeDataArray.isEmpty {}
```

2020-09-22 07:06 UTC, yamataku29 commented on RandomChoiceApp/Controller/RandomChoiceViewController.swift
> +            resultGenreName = (element?.genreName ?? "???") as String
ソースコードを詳しく見ていないのですが、ここは`as String`は不要ではないですかね？
勘違いであればこのままでよいのですが👏

2020-09-22 07:07 UTC, yamataku29 commented on RandomChoiceApp/Controller/ListViewController.swift
> -        let cancelAction = UIAlertAction(title: "キャンセル", style: .cancel, handler: { _ -> Void in
👍

2020-09-22 07:12 UTC, fuchi0741 commented
@yamataku29 
クローズするPRにも関わらずレビューありがとうございます！
また修正したものを別のPRでメンションをつけてレビュー依頼させていただきます！