【WIP】編集機能追加
HaraFuchi/RandomChoiceApp pull request #64
Opened 2020-09-17 11:23 UTC by AyanoHara

**概要**
・データの編集機能追加

2020-09-22 07:52 UTC, AyanoHara commented
@yamataku29  @fuchi0741 
編集機能を追加しました。レビューお願いします。

2020-09-22 09:12 UTC, fuchi0741 requested changes
@AyanoHara 
コメントしましたー！

2020-09-22 09:12 UTC, fuchi0741 commented on RandomChoiceApp/Controller/EditViewController.swift
> +import Firebase
Model化ができているのであれば、`import Firebase`は不要なはず！

2020-09-22 09:12 UTC, fuchi0741 commented on RandomChoiceApp/Controller/EditViewController.swift
> +                self.crudModel.editStoreData(store: self.editStoreNameString ?? "???", place: self.editPlaceNameString ?? "???", genre: self.editGenreNameString ?? "???", childID: self.childID)
???がマジックナンバーになっているので、変数を作成して???の説明を行うと良さそう！
参考: https://github.com/HaraFuchi/RandomChoiceApp/pull/66

2020-09-22 09:12 UTC, fuchi0741 commented on RandomChoiceApp/Controller/EditViewController.swift
> +                self.crudModel.editStoreData(store: self.editStoreNameString ?? "???", place: self.editPlaceNameString ?? "???", genre: self.editGenreNameString ?? "???", childID: self.childID)
ここできるなら、1つのメソッドを作成した方が見やすそう！

2020-09-22 09:12 UTC, fuchi0741 commented on RandomChoiceApp/Model/StoreDataCrudModel.swift
> +        ref.child(Auth.auth().currentUser!.uid).child(childID!).updateChildValues(newEditData)
`  guard let childKey = childID else { return }
ref.child(Auth.auth().currentUser!.uid).child(childID!).updateChildValues(newEditData)`

2行目の`childID!`を`childKey`に変更すると!を使わずにすみそう！

2020-09-22 09:13 UTC, fuchi0741 commented
> **clone コマンド**
> git clone [git@github.com](mailto:git@github.com):HaraFuchi/QuestionApp.git -b feature/add-function-update
> 
> **Trello**
> 編集ページの機能追加
> 
> **概要**
> ・データの編集機能追加
> ・ハードコーディング対応
> ・リファクタリング
> 
> **レビューで見て欲しいポイント**
> ・編集機能が使用できるか
> 
> **参考URL**
> https://qiita.com/imajoriri/items/f4080f67e08c0b529120
> https://qiita.com/buntafujikawa/items/d798ef65b2bba1677cd0
> 
> **実機build/期待通りの挙動をするか**
> OK

@AyanoHara すまん。clone コマンドが別のアプリのリンクになっているから修正よろ！

2020-09-22 11:00 UTC, AyanoHara commented
@fuchi0741 
指摘事項を修正しました。確認お願いします！

2020-09-22 11:05 UTC, yamataku29 requested changes
いくつかコメント入れました🙆‍♂️

2020-09-22 11:05 UTC, yamataku29 commented on RandomChoiceApp/Controller/EditViewController.swift
> +        case 2: editGenreNameString = textField.text
ここでもマジックナンバーが出てきてしまっているので、これを避ける為にenumを上手く活用しましょう💡

```swift
// enum名は仮置なので適切に変更してください
enum TextfieldType: Int { 
    case store
    case place
    case genre
}

    let textFieldType = TextfieldType(rawValue: indexNumber)
    switch textFieldType {
    case .store: editStoreNameString = textField.text
    case .place: editPlaceNameString = textField.text
    case .genre: editGenreNameString = textField.text
    }
```

2020-09-22 11:05 UTC, yamataku29 commented on RandomChoiceApp/Controller/EditViewController.swift
> +        default: break
本来switch文は上記の様にenumなどに書き換えて定義されることが望ましいため、`default`は使わない方が良いです。

これは何故使わない方がいいかというと、例えば上記で言えば`TextfieldType`の`case`が今後増えたと仮定しましょう。

そうした場合、ここで`default`が書かれてしまっていると、新たに増えた`case`が`default`に吸収されてしまい、コンパイルエラーが出ないのですね。

基本的にcaseが増えた場合というのは、新たにcaseを定義し直さなければならないことの方が多いため、ここでコンパイルエラーが出ないということはそれだけで「バグの温床」になり得るということと同義なのですね。

以上の観点から、switch文において`default`が出てきたら「これはまずい」という感覚を持つようにするとよいですね💁‍♂️

2020-09-22 11:05 UTC, yamataku29 commented on RandomChoiceApp/Controller/EditViewController.swift
> +        if editStoreNameString == "" {
Stringにはせっかく便利なプロパティが用意されているので、`.isEmpty`を使って条件式を定義するようにしましょう👍

2020-09-22 23:37 UTC, fuchi0741 commented on RandomChoiceApp/Controller/EditViewController.swift
>      @IBOutlet weak var tableView: UITableView!
@yamataku29 
IBプロパティにアクセス修飾子ですが、以下のようなイメージでしょうか？
`@IBOutlet private weak var tableView: UITableView!`

> 当該プロパティが「外部から参照されていないことを担保している」ということが直感的に分かる。
> 当該プロパティが今後削除される際に「このクラス以外は参照されていないはずなので、影響範囲はこの当該クラス内に留まる」ということがすぐに分かる

この視点めっちゃ納得です！新しい視点を手に入れました笑

@AyanoHara 
工数がまあまあかかりそうなので、チケット作成しました！
なので今回のPRでは修正しなくで大丈夫です！
> 外部参照されていないプロパティは全部privateにする

2020-09-22 23:42 UTC, fuchi0741 commented on RandomChoiceApp/Controller/EditViewController.swift
> +        case 2: editGenreNameString = textField.text
メモ
上記のようなSwift文もマジックナンバー扱いなんですね、、、！
マジックナンバーがダメという知識はありましたが、まだまだ程度が甘かったです😆

@AyanoHara 
今回の編集に関する部分はenumを使って挑戦してみて！

他にもSwift文でマジックナンバーを乱用しているのでチケット化

> swift文のマジックナンバーを避ける

2020-09-22 23:45 UTC, fuchi0741 commented on RandomChoiceApp/Controller/EditViewController.swift
> +        default: break
メモ
swiftとenumは相性がいい。
switch文においてdefaultが出てきたら「これはまずい」という感覚を持つ
→enumを使って回避する
→またenumを使用すると、caseが増えた時にコンパイルエラーがおきない

2020-09-22 23:47 UTC, fuchi0741 commented on RandomChoiceApp/Controller/EditViewController.swift
> +        if editStoreNameString == "" {
@AyanoHara これ今回の差分以外も修正お願いしますー！
難しそうだったらチケットを切ってください！

2020-09-22 23:50 UTC, fuchi0741 commented
> @fuchi0741
> 指摘事項を修正しました。確認お願いします！

@AyanoHara 
自分が最初にした指摘事項に関しては大丈夫です！
あとはヤマタクさんからの指摘の修正をよろしくです！

2020-09-23 01:46 UTC, yamataku29 commented on RandomChoiceApp/Controller/EditViewController.swift
> +        if editStoreNameString == "" {
@fuchi0741 @AyanoHara 
今回の差分以外＝プロジェクト内全てが対象範囲になりそうですが、その範囲を修正するのであればPRは分けましょう👏
なぜかというと、その修正は今回のPRの本来の目的から外れるリファクタリングタスクなので、関係の無い差分が含まれてしまい、管理が煩雑になるためですね。

featureとrefactorは明示的にPRを分ける癖をつけましょう👍
これは目的別にPRを分ける。という意味でもありますね。

2020-09-23 03:11 UTC, fuchi0741 commented on RandomChoiceApp/Controller/EditViewController.swift
> +        if editStoreNameString == "" {
@yamataku29 
承知しました！
別のチケットを切りました！

あとブランチ名は開発中は基本的に`feature/xxx`にしていましたが、
リファクタリングタスクの場合は`refactor/xxx`というブランチもあるのですね！

@AyanoHara チケット追加しましたー！
> 値がないことを示す場合はisEmptyプロパティで実装する

2020-09-24 06:50 UTC, AyanoHara commented
@yamataku29 
指摘事項修正しました。お手隙の際に確認お願い致します。

2020-09-24 06:50 UTC, AyanoHara commented on RandomChoiceApp/Controller/EditViewController.swift
> +        if editStoreNameString == "" {
@yamataku29 

以前.isEmptyを使用した場合`== true`は省略可能とのことでしたが ( #66 )、今回`== true`を省略しようとした際にこのようなエラーが出ました。

       ```
 if editStoreNameString?.isEmpty {
            editStoreNameString = nil
        }

```
【エラー内容】
`Value of optional type 'Bool?' must be unwrapped to a value of type 'Bool'`

今回の場合、`editStoreNameString`をOptional Chainingしているためbool値がラップされて返されている。それが原因で == true を省略できないということでしょうか？

2020-09-24 06:58 UTC, AyanoHara commented on RandomChoiceApp/Controller/EditViewController.swift
> +        case 2: editGenreNameString = textField.text
私もswitch文で使われる数字もマジックナンバーに含まれるということを初めて知りました。今後はenumに書き換えるよう意識していきます！

2020-09-24 07:14 UTC, AyanoHara commented on RandomChoiceApp/Controller/EditViewController.swift
> +        default: break
@yamataku29 
enumのswitch文の最後に`.none`というcaseを生成するようエラーメッセージで促されたのですが、これは`categoryNameText`がオプショナル型のためなのでしょうか？

2020-09-24 12:51 UTC, yamataku29 commented on RandomChoiceApp/Controller/EditViewController.swift
>      @IBOutlet weak var tableView: UITableView!
> IBプロパティにアクセス修飾子ですが、以下のようなイメージでしょうか？

ですね👍

2020-09-24 12:52 UTC, yamataku29 commented on RandomChoiceApp/Controller/EditViewController.swift
> +        case 2: editGenreNameString = textField.text
StringだろうとIntだろうとDoubleだろうと、はたまたenumだろうとstructだろうと変数以外の固定値は全てマジックナンバーだと思えば間違いないですね👌

2020-09-24 12:53 UTC, yamataku29 commented on RandomChoiceApp/Controller/EditViewController.swift
> +        default: break
> enumのswitch文の最後に.noneというcaseを生成するようエラーメッセージで促されたのですが、これはcategoryNameTextがオプショナル型のためなのでしょうか？

具体的なエラー分を見ていないのでなんとも言えないですが、状況から想像するに恐らくその認識で合っていると思います👌

2020-09-24 12:57 UTC, yamataku29 commented on RandomChoiceApp/Controller/EditViewController.swift
> +        if editStoreNameString == "" {
> 今回の場合、editStoreNameStringをOptional Chainingしているためbool値がラップされて返されている。それが原因で == true を省略できないということでしょうか？

いい考察ですね。
そのとおりです👍

この場合は下記の様に書くといいでしょう👌

```swift
if let editStoreNameString = editStoreNameString, editStoreNameString.isEmpty {
        editStoreNameString = nil
}
```

もし上記の`let editStoreNameString = editStoreNameString`で`redeclaration`のようなエラーが出る場合は、変数名を`editStoreNameString`以外に変えて上げればOKです。
e.g. `nameText`など

2020-09-24 12:58 UTC, yamataku29 commented on RandomChoiceApp/Controller/EditViewController.swift
> +        if editStoreNameString == "" {
@AyanoHara

2020-09-24 13:02 UTC, yamataku29 commented on RandomChoiceApp/Controller/EditViewController.swift
> +        if editStoreNameString == "" {
おっと、すみません。
指摘内容が間違っていました🙏

ここでは`editStoreNameString`がnilかもしくは空文字だった場合にif文のスコープに入る。というロジックのはずなので、正しくは下記になりますね。

```swift
if editStoreNameString == nil || editStoreNameString == "" {
    print("is nil")
}
```

2020-09-24 13:03 UTC, yamataku29 commented
@fuchi0741 @AyanoHara 
コメントを返したので確認ください👍

2020-09-26 03:41 UTC, AyanoHara commented on RandomChoiceApp/Controller/EditViewController.swift
> +        default: break
@yamataku29 
承知しました。ありがとうございます！

2020-09-26 03:45 UTC, AyanoHara commented on RandomChoiceApp/Controller/EditViewController.swift
> +        if editStoreNameString == "" {
@yamataku29 
ご丁寧にありがとうございます。

```
if editStoreNameString == nil || editStoreNameString == "" {
    print("is nil")
}
```

こちらを参考に修正致しました。

2020-09-26 03:45 UTC, AyanoHara commented
@yamataku29 
指摘事項修正しましたので、確認お願い致します。

2020-09-26 08:01 UTC, fuchi0741 requested changes
@AyanoHara 
コメントしましたー！

2020-09-26 08:01 UTC, fuchi0741 commented on RandomChoiceApp/Controller/EditViewController.swift
> +    }
@AyanoHara cc @yamataku29 
少し冗長なような気がするので、下記の書き方で問題ないと思いますがいかがでしょうか？
```swift
if editStoreNameString == "" {
    editStoreNameString = nil
}
```

また以下の似たようなロジックをしたメソッドがあるので、このメソッドの条件に空文字だった場合も追加できたりできますか？
それだと、textConvertNil()メソッドがそもそも不要になると思います！
```swift
private func convertValueNil() {
        if editStoreNameString == LiteralQuestions.questions {
            editStoreNameString = nil
        }
        if editPlaceNameString == LiteralQuestions.questions {
            editPlaceNameString = nil
        }
        if editGenreNameString == LiteralQuestions.questions {
            editGenreNameString = nil
        }
    }
```

2020-09-26 09:42 UTC, yamataku29 commented on RandomChoiceApp/Controller/EditViewController.swift
> +    }
> 少し冗長なような気がするので、下記の書き方で問題ないと思いますがいかがでしょうか？

いえ、Stringのnilと空文字は全く別物で、これはそれぞれ異なる条件処理を示しているので冗長ではありません💁‍♂️
試しにPlaygroundなどで実際にコードを書いて確認して、みるとよいでしょう👌

2020-09-26 12:06 UTC, fuchi0741 commented on RandomChoiceApp/Controller/EditViewController.swift
> +    }
それは失礼しました！
ちょっと確認してみます！

2020-09-26 12:24 UTC, fuchi0741 commented on RandomChoiceApp/Controller/EditViewController.swift
> +    }
すいません。言葉足らずでした！
nilを空文字の違いは理解できているのですが、
例えば、editStoreNameStringがnilだった場合nilをいれるコードが必要なのかの理解が追いつけていないですね、、、
```swift
if editStoreNameString == nil  {
        editStoreNameString = nil
}
```

2020-09-26 12:37 UTC, yamataku29 commented on RandomChoiceApp/Controller/EditViewController.swift
> +    }
あ、たしかにそうですね🤭
その認識で正しいと思います！
処理内容をよく見ずにコメントしてました🥺💧

2020-09-26 13:07 UTC, fuchi0741 commented on RandomChoiceApp/Controller/EditViewController.swift
> +    }
よかったです！安心しました
そこで1番最初のコメントに戻るのですが、

現ソースコードに`private func convertValueNil()`というメソッドがあります。
このメソッドは**ある条件だとnilをいれる**というメソッドで、今回新たに書いた`private func textConvertNil()`と同じ**ある条件だとnilをいれる**というメソッドだと思います。

そのため既存の`private func convertValueNil()`メソッドに異なる条件処理を示す方法の方がようのではという意図でコメントを書かせていただきました！

2020-09-27 06:50 UTC, AyanoHara commented on RandomChoiceApp/Controller/EditViewController.swift
> +    }
既存のメソッドである`private func convertValueNil()`の条件を追加してメソッドを一つにまとめました。
確認お願いします。

2020-09-27 06:51 UTC, AyanoHara commented
@yamataku29  @fuchi0741 
指摘事項修正しました。確認お願い致します。

2020-09-27 08:47 UTC, yamataku29 approved these changes
良いと思います！
LTGM🙆‍♂️🎉

2020-09-27 09:05 UTC, fuchi0741 approved these changes
@AyanoHara LGTM👍
手元で動作確認しても問題ありませんでしたーーー！

2020-09-27 09:33 UTC, merged