開発と本番環境でインストールを分ける
HaraFuchi/RandomChoiceApp pull request #65
Opened 2020-09-22 06:30 UTC by fuchi0741

## clone コマンド
git clone git@github.com:HaraFuchi/RandomChoiceApp.git -b feature/separete-release-and-debug

## Trello
実機ビルドで開発と本番環境で分ける

## 概要
アプリをインストールするとき、開発環境と本番環境でアプリを分けることができなかった。
そのため開発環境(buildした時)と本番環境(App storeからインストール)でアプリを分けるようにした。

BundleIdentifier を分けることにより実現

## レビューで見て欲しいポイント
開発環境と本番環境でアプリが2種類インストールされるかどうか？

## 参考URL
【Xcode11.5】開発／本番環境でインストールを分ける
https://exgyaruo.com/xcode/separate-appsote-to-debug

## 実機build/期待通りの挙動をするか
OK

## 補足
なし

2020-09-22 07:14 UTC, yamataku29 requested changes
確認したところ、Build Schemeが追加されていない様なので、Develop(開発)とRelease(本番)を分けてビルドや実行が出来ないようです🙅‍♂️

下記を参考にBuild Schemeを追加しましょう👏
https://dev.classmethod.jp/articles/xcode-build-environment-adding-scheme/

2020-09-24 04:53 UTC, fuchi0741 commented
@yamataku29 @AyanoHara 
Build Schemeを追加しましたー！
お時間のある時にレビューお願いしますー！

2020-09-24 13:04 UTC, yamataku29 commented
@fuchi0741 
コンフリクトしているようなので、先にそちらの解決をお願いします🙆‍♂️

2020-09-26 07:15 UTC, fuchi0741 commented
@yamataku29 @AyanoHara 
コンフリクト解消しましたー！
お時間のある時にレビューお願いしますー！

2020-09-26 07:31 UTC, fuchi0741 commented
@yamataku29 
今のPR時点での解釈を手書きではありますが、まとめてみました！
ステージングや本番環境にも当然対応させた方がいいですよね?

![IMG_6474](https://user-images.githubusercontent.com/50318372/94335262-4b259700-0015-11eb-887e-8f32ec918aa5.JPG)

2020-09-26 09:40 UTC, yamataku29 commented
> 今のPR時点での解釈を手書きではありますが、まとめてみました！

少し認識に齟齬があるかもですね！
スキームはあくまでフラグと一緒なので、ビルドした際にどのフラグを使用するのかを切り替えているだけなのですね👍
なので、特段階層などの概念はありません。

それと確認したのですが、僕の手元だとまだスキームが1つしか無いんですよね🤔
<img width="388" alt="スクリーンショット 2020-09-26 18 37 23" src="https://user-images.githubusercontent.com/17525335/94337711-9a74c300-0027-11eb-99d8-86e4d27cad20.png">

正常にスキームがつい追加されている場合だと、下記の様にスキームが複数選択できるはずなんですよね。
<img width="383" alt="スクリーンショット 2020-09-26 18 37 13" src="https://user-images.githubusercontent.com/17525335/94337717-a9f40c00-0027-11eb-8f54-7d0b53cf07b6.png">

2020-09-26 13:14 UTC, fuchi0741 commented
> > 今のPR時点での解釈を手書きではありますが、まとめてみました！
> 
> 少し認識に齟齬があるかもですね！
> スキームはあくまでフラグと一緒なので、ビルドした際にどのフラグを使用するのかを切り替えているだけなのですね👍
> なので、特段階層などの概念はありません。
> 
> それと確認したのですが、僕の手元だとまだスキームが1つしか無いんですよね🤔
> <img alt="スクリーンショット 2020-09-26 18 37 23" width="388" src="https://user-images.githubusercontent.com/17525335/94337711-9a74c300-0027-11eb-99d8-86e4d27cad20.png">
> 
> 正常にスキームがつい追加されている場合だと、下記の様にスキームが複数選択できるはずなんですよね。
> <img alt="スクリーンショット 2020-09-26 18 37 13" width="383" src="https://user-images.githubusercontent.com/17525335/94337717-a9f40c00-0027-11eb-8f54-7d0b53cf07b6.png">

自分もclone確認したのですが、確認できなかったです、、！
(自分のローカルファイルを誤って削除しちゃって再現が難しくなってしましました、、。)

調べてみると恐らくsharedのチェックマークを外してしまったのが原因かと思われます。

再現するのが難しくなったので、このPRはクローズにして新しくブランチを切って再度PRをあげようと思います！

2020-09-26 13:17 UTC, fuchi0741 commented
@yamataku29 
> 少し認識に齟齬があるかもですね！
> スキームはあくまでフラグと一緒なので、ビルドした際にどのフラグを使用するのかを切り替えているだけなのですね👍
> なので、特段階層などの概念はありません。

すいません。ここですが普段開発をするときは-Devのスキームを使用をするという認識であっています？？

2020-09-27 05:27 UTC, fuchi0741 commented
新らしくbranchを切るのでクローズにする

2020-09-27 05:27 UTC, closed without merging

2020-09-27 08:43 UTC, yamataku29 commented
> すいません。ここですが普段開発をするときは-Devのスキームを使用をするという認識であっています？？

そういうことですね👍