データを取ってくる前にさいころをタップするとnilが返らないように修正
HaraFuchi/RandomChoiceApp pull request #66
Opened 2020-09-22 06:57 UTC by fuchi0741

## clone コマンド
git clone git@github.com:HaraFuchi/RandomChoiceApp.git -b feature/fix-dice-nil

## Trello
起動直後にサイコロを押すとnilの情報が帰ってくるので/ボタンを押せなくする

## 概要
データを取ってくる前にさいころをタップするとnilが返らないようする
→guard文を使用してnilを返ってくる

## レビューで見て欲しいポイント
nilを回避する方法としてguard文を使用したが、より良い方法はあるか？

## 参考URL
特になし

## 実機build/期待通りの挙動をするか
OK

## 補足
さいころを押しても、無視される仕様になったので、
さいころを若干透明にして押せなくするか、アラートを出すかの対処が必要かも？

2020-09-22 07:20 UTC, yamataku29 requested changes

2020-09-22 07:20 UTC, yamataku29 commented on RandomChoiceApp/Controller/RandomChoiceViewController.swift
> +        guard let _ = element else { return }
ここはせっかくguard-let文を使ったOptional-Bindingを利用しているので、それを活用しましょう👏
あとStringへのキャストしなくても型推論でStringであることが自明なので、これも省略して良いと思います💡


```swift
func didTapDiceButton() {
    let storeDataArray = crudModel.storeDataArray
    
    guard let element = storeDataArray.randomElement() else { return }
    
    resultStoreName = element.storeName ?? "???"
    resultPlaceName = element.placeName ?? "???"
    resultGenreName = element.genreName ?? "???"
    
    tableView.reloadData()
}

```

2020-09-22 07:20 UTC, yamataku29 commented on RandomChoiceApp/Controller/RandomChoiceViewController.swift
> +        guard let _ = element else { return }
あとマジックナンバーはできるだけ避けましょう👏
ここでいう`???`は固定値(=マジックナンバー)なので、これの意味を説明するためにも変数にした方が良いですね。

```swift
private var emptyNameText: String { return "???" }
func didTapDiceButton() {
  ...
}
```

2020-09-22 07:20 UTC, yamataku29 commented on RandomChoiceApp/Controller/RandomChoiceViewController.swift
> +        guard let _ = element else { return }
Cc @AyanoHara

2020-09-22 07:33 UTC, fuchi0741 commented
@yamataku29 
レビュー指摘の修正しました！
お時間のある時に再度レビューお願いします！

2020-09-22 07:37 UTC, fuchi0741 commented on RandomChoiceApp/Controller/RandomChoiceViewController.swift
> +        guard let _ = element else { return }
@yamataku29 
マジックナンバーを避けるために、ハードコーディングのものをまとめたファイル(`LiteralConstrains.swift`)を作ってあるのですが、
`private var emptyNameText: String { return "???" }`

こっちの方がわかりやすくていいですね！
ありがとうございます！

2020-09-22 07:47 UTC, fuchi0741 commented
@yamataku29 すいません、質問です。
> ここの== trueは省略可能なので、書かない方がよいですね💁‍♂️
> Swiftでは、真偽値が自明な場合はイコールオペレーターを省略するのが慣習なので、その様にリファクタリングするとよいでしょう。

こちらですが、
== trueを書いた方が可読性は上がるかなと思い、あえて書いた記憶です！
`isEmpty`のプロパティを使用するときは一般的にtrueの場合でfalseのときはあまり使わないから、省略してもよいという判断ですか？

2020-09-22 10:42 UTC, yamataku29 commented
> こちらですが、
== trueを書いた方が可読性は上がるかなと思い、あえて書いた記憶です！
isEmptyのプロパティを使用するときは一般的にtrueの場合でfalseのときはあまり使わないから、省略してもよいという判断ですか？

ちょっと説明が不足しいたかもですね。
可読性が低いのと、後は自明な条件式をあえて冗長に書くことに対して恩恵が無い。という理由もリファクタリング観点ですね👏

`.isEmpty`というプロパティは[そもそもの定義元](https://developer.apple.com/documentation/swift/array/1688398-isempty)を見れば分かるのですが、Boolが返ってくるプロパティですよね。

つまり`.isEmpty`とは、「Boolであること」が自明な訳です。
「Boolであることが自明」ということは、trueかfalseかのいずれかしか入らないということと同義なので、意訳すると下記のようなコードを書いているのとイコールなのですね。

```swift 
if true == true {
  // isEmpty == trueの処理 
}

if true == false {
  // isEmpty == falseの処理 
}
```

これを見たら恐らく誰でも「これは冗長である」と理解できると思いますが、要は現状のコードはこの様に書かれているということですね💁‍♂️

確かにこれは「初学者から見ると」可読性は高いかも知れませんが、コードとしてはイマイチですよね。

2020-09-22 10:44 UTC, yamataku29 approved these changes
うん！スッキリしていいですね！
LGTM🙆‍♂️🎉

2020-09-22 23:18 UTC, fuchi0741 commented
> > こちらですが、
> > == trueを書いた方が可読性は上がるかなと思い、あえて書いた記憶です！
> > isEmptyのプロパティを使用するときは一般的にtrueの場合でfalseのときはあまり使わないから、省略してもよいという判断ですか？
> 
> ちょっと説明が不足しいたかもですね。
> 可読性が低いのと、後は自明な条件式をあえて冗長に書くことに対して恩恵が無い。という理由もリファクタリング観点ですね👏
> 
> `.isEmpty`というプロパティは[そもそもの定義元](https://developer.apple.com/documentation/swift/array/1688398-isempty)を見れば分かるのですが、Boolが返ってくるプロパティですよね。
> 
> つまり`.isEmpty`とは、「Boolであること」が自明な訳です。
> 「Boolであることが自明」ということは、trueかfalseかのいずれかしか入らないということと同義なので、意訳すると下記のようなコードを書いているのとイコールなのですね。
> 
> ```swift
> if true == true {
>   // isEmpty == trueの処理 
> }
> 
> if true == false {
>   // isEmpty == falseの処理 
> }
> ```
> 
> これを見たら恐らく誰でも「これは自明なことを冗長にして書いてある」と理解できると思いますが、要は現状のコードはこの様に書かれているということですね💁‍♂️
> 
> 確かにこれは「初学者から見ると」可読性は高いかも知れませんが、コードとしてはイマイチですよね。

ご丁寧にありがとうございます！
確かに公式ドキュメントの説明や例文を見ると
`A Boolean value indicating whether the collection is empty.
`

```swift
let horseName = "Silver"
if horseName.isEmpty {
    print("My horse has no name.")
} else {
    print("Hi ho, \(horseName)!")
}
// Prints "Hi ho, Silver!")

```

という記述を見ると**isEmpty**のBool値を省略した場合は**isEmpty**は**true**が入っていると考えると、**== true** と書くのは冗長だと感じますね！

2020-09-22 23:25 UTC, fuchi0741 commented on RandomChoiceApp/Controller/RandomChoiceViewController.swift
> +        guard let _ = element else { return }
@yamataku29 質問させてください！
マジックナンバーを避けるために以下のコードを使用することは納得しました！
`private var emptyNameText: String { return "???" }
`

ただ、自分がコードを書く場合は以下のように記述書くと思います。
`private var emptyNameText: String  =  "???" 
`

いまいち`return`を使用する恩恵を感じられていないのですが、なぜ`return`を使用する恩恵はなんなのでしょうか？

回答お待ちしてます。よろしくお願いしますー！

2020-09-23 01:43 UTC, yamataku29 commented on RandomChoiceApp/Controller/RandomChoiceViewController.swift
> +        guard let _ = element else { return }
それはどちらでも構いませんよ👌
僕は普段`private extension`内でこういったマジックナンバーの変数を定義することが多いので、癖でComputed Propertyにしているだけなので💁‍♂️

extensionブロック内に記載しないのであれば、Stored Propertyにしても問題ないですね。
ただ、Computed PropertyとStored Propertyの特性や違いについては理解しておいた方がよいです👍

2020-09-26 03:47 UTC, AyanoHara approved these changes
LGTM!!

2020-09-26 07:05 UTC, fuchi0741 commented on RandomChoiceApp/Controller/RandomChoiceViewController.swift
> +        guard let _ = element else { return }
メモ:Computed PropertyとStored Propertyについてインプット

2020-09-26 07:06 UTC, fuchi0741 commented
マージしますーー！

2020-09-26 07:07 UTC, merged