【WIP】設定画面を作成
HaraFuchi/RandomChoiceApp pull request #90
Opened 2020-11-23 17:59 UTC by AyanoHara

## clone コマンド
git clone git@github.com:HaraFuchi/RandomChoiceApp.git -b feature/add-SettingVC

## Trello
お問い合わせなどの設定画面の作成
## 概要
・設定画面を新規作成

## レビューで見て欲しいポイント

## 参考URL

## 実機build/期待通りの挙動をするか

 
## 補足

2020-12-01 05:22 UTC, AyanoHara commented
@yamataku29 
プルリクのWIPを外す前に、ハードコーディング対応の範囲について少し疑問に思ったことがあるので質問させて下さい。

現段階で文字列や数字はどんな場合でも全てハードコーディングを避けるべきだという認識でいるのですが、あえてハードコーディングを許容する場面はあるのでしょうか。

お手隙の際に回答よろしくお願いします。

2020-12-01 05:32 UTC, yamataku29 commented
@AyanoHara 
そうですね、やむを得ずハードコーディングを許容するケースもあります。
例えばアプリ固有で使用する文字列があったり、APIのステータスコードの定義をする場合などは定数としてハードコーディングを行うことはよくありますね💁‍♂️💡

2020-12-01 06:48 UTC, AyanoHara commented
@yamataku29 
なるほど！場合によってはハードコーディングを許容する場面もあるのですね。
勉強になりました、ありがとうございます🙇‍♀️

2020-12-01 06:49 UTC, AyanoHara commented
@yamataku29 
なるほど！場合によってはハードコーディングを許容する場面もあるのですね。
勉強になりました、ありがとうございます🙇‍♀️

2020-12-01 15:22 UTC, AyanoHara commented
> ## clone コマンド
> git clone [git@github.com](mailto:git@github.com):HaraFuchi/RandomChoiceApp.git -b feature/add-SettingVC
> 
> ## Trello
> お問い合わせなどの設定画面の作成
> 
> ## 概要
> ・設定画面を新規作成
> ・アプリ内でメール画面を開けるようにする
> ・アプリからAppStoreのレビューページ に飛ぶ
> ・現在のアプリバージョンを記載
> 
> ## 追加したページのUI
> ![IMG_8702](https://user-images.githubusercontent.com/65425673/100759518-0adafe80-3434-11eb-8eda-1960cc09b422.jpg) ![IMG_8703](https://user-images.githubusercontent.com/65425673/100759529-0d3d5880-3434-11eb-906c-21ac3d46faeb.jpg)
> 
> ## レビューで見て欲しいポイント
> ・メーラーが正しく起動するか、また送信できるか
> ・外部リンク(AppStoreのレビューページ)に飛べるかどうか
> ・正しいアプリバージョンが反映されているか(V1.2.0)
> ・セルのアクセサリの位置にバージョン記載をしたかったため、accessoryViewを使用したがうまくいかず、妥協案として新たなUILabelを設置。他に案はないか？
> 
> ## 参考URL
> https://zenn.dev/riscait/articles/mail-compose-for-swift
> 
> ## 実機build/期待通りの挙動をするか
> OK
> 
> ## レビュー依頼
> @fuchi0741
> 
> レビューお願いしますー！
> 
> ## 補足
> ⚠️外部リンクとメーラーを使用しているので、シュミレーターではなく実機でビルドをお願いします。

2020-12-01 15:24 UTC, AyanoHara commented on RandomChoiceApp/Controller/SettingViewController.swift
> +        }
## 補足

この部分のマジックナンバーは、他のクラスにも存在するので別ブランチでまとめて対応します🙌

2020-12-03 16:22 UTC, fuchi0741 commented
@AyanoHara 動作確認のみ一旦しましたが問題なさそうですー！

別チケットでメールとかでお問い合わせがきたやつをSlackが感知できるようにしてみたい、、。
お問い合わせに限らず全ての通知、、！

2020-12-03 16:38 UTC, fuchi0741 reviewed
Cellに > があるとCellがタップできることが直感的にわかるのでいいと思いました！

2020-12-03 16:38 UTC, fuchi0741 commented on RandomChoiceApp/Controller/SettingViewController.swift
> +    @IBAction func didTapGoBackButton(_ sender: UIBarButtonItem) {
`didTapGoBackButton`の命名の`didTapBackButton`でGoがなくても十分伝わるのではと思いました！

細かくて、人にもよりそうだけど

2020-12-03 16:38 UTC, fuchi0741 commented on RandomChoiceApp/View/Cells/SettingTableViewCell.swift
> +    }
使用しない予定のメソッドなので削除していいかと思いましたー！

2020-12-03 16:56 UTC, fuchi0741 requested changes
@AyanoHara コメントしましたー！
確認お願いしますー！

2020-12-03 16:56 UTC, fuchi0741 commented on RandomChoiceApp/Controller/SettingViewController.swift
> +    private var appVersion = Bundle.main.object(forInfoDictionaryKey: BundleIdentifierLiteral.appVersion) as! String
どちらもletで問題なさそうな気がしますー！

2020-12-03 16:56 UTC, fuchi0741 commented on RandomChoiceApp/Controller/SettingViewController.swift
> +            showAlertNoEmailAddress()
有効なメールアドレスでない場合にエラーハンドリングができるか手動テストをしたいのですが、エラーを起こす再現手順ってわかってたりする？

2020-12-03 16:56 UTC, fuchi0741 commented on RandomChoiceApp/View/Cells/SettingTableViewCell.swift
> +    @IBOutlet weak var subTitleLabel: UILabel!
せっかくなんで、ここもアクセス修飾子追加で！

2020-12-03 16:56 UTC, fuchi0741 commented on RandomChoiceApp/View/Cells/SettingTableViewCell.xib
> +                    <constraint firstAttribute="trailingMargin" secondItem="wEo-9i-CZN" secondAttribute="trailing" constant="-8" id="QzF-b2-chn"/>
制約でマイナスを使用しているのが気になりました、、、。

2020-12-03 17:00 UTC, fuchi0741 reviewed
@AyanoHara コメント追加ー！

2020-12-03 17:00 UTC, fuchi0741 commented on RandomChoiceApp/LiteralConstraints.swift
> +    static let appStoreReviewUrl = "https://apps.apple.com/jp/app/%E3%81%95%E3%81%84%E3%81%93%E3%82%8Dde%E3%81%94%E3%81%AF%E3%82%93/id1528912786?mt=8&action=write-review"
URLはなんのURLかわからなくなりそうなので、コメントを追加してもらえると嬉しいですー！

2020-12-03 17:00 UTC, fuchi0741 commented on RandomChoiceApp/View/Cells/SettingTableViewCell.swift
> +    var indexPathNumber:Int?//登録画面で繰り返すCellを分別する変数
?の後ろにスペースがないのが気になりました、、。

2020-12-03 17:03 UTC, AyanoHara commented on RandomChoiceApp/Controller/SettingViewController.swift
> +            showAlertNoEmailAddress()
メールアプリを一度アンインストールして、アプリを起動できない状態にしたらできました。
あとはインストールし直して、メールアドレスの設定(ログイン)をする前の状態でも可能です！

2020-12-03 17:04 UTC, fuchi0741 commented on RandomChoiceApp/Controller/SettingViewController.swift
> +    private var appVersion = Bundle.main.object(forInfoDictionaryKey: BundleIdentifierLiteral.appVersion) as! String
settingCell は let だとエラーでるのか、、。

2020-12-03 17:12 UTC, fuchi0741 commented on RandomChoiceApp/Controller/SettingViewController.swift
> +            showAlertNoEmailAddress()
確認できたー！
OK押したら、設定アプリのアドレスを追加する画面に遷移してあげるのが丁寧だと思うけど今回はパスでいいかなー
<img width="223" alt="スクリーンショット 2020-12-04 2 10 41" src="https://user-images.githubusercontent.com/50318372/101063241-f33b7b80-35d5-11eb-9524-940b1c443067.png">

2020-12-04 09:26 UTC, fuchi0741 commented
やまたくさんにお聞きしたいこと
→Model化できる部分はあるかどうか

2020-12-04 10:12 UTC, AyanoHara commented on RandomChoiceApp/Controller/SettingViewController.swift
> +    @IBAction func didTapGoBackButton(_ sender: UIBarButtonItem) {
承知しましたー！
Outlet接続の方も一緒にRenameします！

2020-12-04 10:15 UTC, yamataku29 commented
このPRを僕がレビューできるタイミングになったらメンション飛ばしてください🙋‍♂️💡

2020-12-04 10:16 UTC, AyanoHara commented on RandomChoiceApp/Controller/SettingViewController.swift
> +    private var appVersion = Bundle.main.object(forInfoDictionaryKey: BundleIdentifierLiteral.appVersion) as! String
settingCellはエラー出るから、assVersionのみ修正加えます。

2020-12-04 10:22 UTC, AyanoHara commented on RandomChoiceApp/View/Cells/SettingTableViewCell.swift
> +    @IBOutlet weak var subTitleLabel: UILabel!
ここは、別クラスで参照されているのでprivateにできません〜💧

2020-12-04 14:58 UTC, AyanoHara commented
@fuchi0741 
修正しました！確認お願いします！

2020-12-04 14:59 UTC, fuchi0741 approved these changes
@AyanoHara LGTM👍

2020-12-04 16:01 UTC, AyanoHara commented
@yamataku29 
お時間ある時にレビューお願いします。

> やまたくさんにみていただきたい箇所
> →Model化できる部分はあるかどうか

この点についても確認お願いします🙇‍♀️

2020-12-05 05:09 UTC, yamataku29 requested changes
いくつかコメントしました👌

> やまたくさんにみていただきたい箇所
→Model化できる部分はあるかどうか

中身を見ましたが、特段モデル化する必要がありそうなものはなかったので、このままでよいと思いますよ💁‍♂️

2020-12-05 05:09 UTC, yamataku29 commented on RandomChoiceApp/View/Cells/SettingTableViewCell.swift
> +    @IBOutlet weak var settingTitleLabel: UILabel!
IB系プロパティは基本的にクラス外から参照させるのは避けた方がよいですね💡
IB系プロパティ(=UI系プロパティ)はViewのライフサイクルを持つプロパティなので、意図せずnilなのに当該プロパティにアクセスしてクラッシュするなどの被害が発生することもありえます💁‍♂️

また、UI系は様々なプロパティを持っているため、これをクラス外からアクセスできるようにしてしまうと、クラス外でできることが膨大に増えてしまうので、バグの温床にもなり得ます。

そのため、IB系プロパティのクラス外アクセスに関しては少し敏感になり過ぎるくらいでも良いでしょう👌

さて、肝心なワークアラウンドについてですが、下記の様に書いてあげるとよさそうですね😌

```swift
class SettingTableViewCell: UITableViewCell {
    
    var indexPathNumber:Int? //登録画面で繰り返すCellを分別する変数
    
    @IBOutlet private weak var settingTitleLabel: UILabel!
    @IBOutlet private weak var subTitleLabel: UILabel!
    
    override func awakeFromNib() {
        super.awakeFromNib()
    }
    
    var isSubTitleLabelHidden: Bool = false {
        didSet {
            subTitleLabel?.isHidden = isSubTitleLabelHidden
        }
    }
    
    var titleText: String = "" {
        didSet {
            settingTitleLabel?.text = titleText
        }
    }
    
    var subTitleText: String = "" {
        didSet {
            subTitleLabel?.text = titleText
        }
    }
}

```

2020-12-05 05:09 UTC, yamataku29 commented on RandomChoiceApp/Controller/SettingViewController.swift
> +            let url = NSURL(string: UrlLiteral.appStoreReviewUrl)
ここは`NSURL`ではなく`URL`型を使用し、且つguard-let文を使ってあげるとスッキリと書けそうですね💁‍♂️

また、`settingCell.indexPathNumber = indexPath.row`はどのcaseでも共通の処理のようなので、switch文のスコープから出してあげるのがよいでしょう😌
※下記のイメージ実装に加えて`SettingCategoryList`を活用することも忘れずに。

```swift
func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    tableView.deselectRow(at: indexPath, animated: true)
    settingCell.indexPathNumber = indexPath.row
    switch indexPath.row {
    case 0:
        composeMail()
    case 1:
        //外部ブラウザでURLを開く
        guard let url = URL(string: UrlLiteral.appStoreReviewUrl),
              UIApplication.shared.canOpenURL(url) else { return }
        UIApplication.shared.open(url)
    case 2: break
    default: break
    }
}
```

2020-12-06 05:46 UTC, AyanoHara commented on RandomChoiceApp/Controller/SettingViewController.swift
> +class SettingViewController: UIViewController, UINavigationBarDelegate, UITableViewDataSource, UITableViewDelegate {
このようにProtocol毎にextensionとして分けることで、可読性を上げられるのですね！
以前、`UITableViewDelegate`と`UITableViewDataSource`をまとめてextensionに分けているコードを見たことがあるのですが、どこまでextensionとして分けるかというのは好みのようなものなのでしょうか？
個人的にはヤマタクさんに提示していただいたようにProtocol毎に分ける方法が分かりやすいので、上記のように修正したいと思います🙌

2020-12-06 05:46 UTC, AyanoHara commented on RandomChoiceApp/Controller/SettingViewController.swift
> +        case 0:
なるほど！
この方法をとることで、`SettingCategoryList`を活用してswitch文で使用していたマジックナンバーも回避できるのですね！enumの理解度が今までよりも深まりました🙇‍♀️

2020-12-06 05:46 UTC, AyanoHara commented on RandomChoiceApp/Controller/SettingViewController.swift
> +        } else {
if文と勘違いしてelse節を使用してしまっていました。ご指摘ありがとうございます！修正します💦

2020-12-06 05:47 UTC, AyanoHara commented on RandomChoiceApp/View/Cells/SettingTableViewCell.swift
> +    @IBOutlet weak var settingTitleLabel: UILabel!
> IB系プロパティ(=UI系プロパティ)はViewのライフサイクルを持つプロパティなので、意図せずnilなのに当該プロパティにアクセスしてクラッシュするなどの被害が発生することもありえます💁‍♂️

IB系のプロパティをクラス外から参照させてしまうと、このような被害の可能性があるのですね。ここまで考えが至らなかったので、とても勉強になります。

2020-12-06 06:21 UTC, yamataku29 commented on RandomChoiceApp/Controller/SettingViewController.swift
> +class SettingViewController: UIViewController, UINavigationBarDelegate, UITableViewDataSource, UITableViewDelegate {
> 以前、UITableViewDelegateとUITableViewDataSourceをまとめてextensionに分けているコードを見たことがあるのですが、どこまでextensionとして分けるかというのは好みのようなものなのでしょうか？
個人的にはヤマタクさんに提示していただいたようにProtocol毎に分ける方法が分かりやすいので、上記のように修正したいと思います🙌

そうですね、どの粒度で分けるかは好みの問題でもありますし、その粒度についても開発チームによってはコーディング規約などで制約を設けているところがありますね💁‍♂️

各個人の好みで決めて良いならそれでもいいし、もしチーム内で統一したいのであればコーディング規約で制約を設ける。というのが一般的でしょう💡

2020-12-07 08:39 UTC, AyanoHara commented on RandomChoiceApp/Controller/SettingViewController.swift
> +            let url = NSURL(string: UrlLiteral.appStoreReviewUrl)
確かに都度URL型にキャストするより断然効率が良いですし、スッキリしますね！🙇‍♀️

2020-12-07 08:46 UTC, AyanoHara commented on RandomChoiceApp/Controller/SettingViewController.swift
> +
ここで`else { return }`を使用することで、switch文の最後に記述していた`default: break`と同義になり削除可能と考え削除したのですがこの認識は正しいでしょうか？

2020-12-07 08:50 UTC, AyanoHara commented
@yamataku29 
修正とコメントをしましたので、お時間あるときに確認お願い致します🙇‍♀️

2020-12-07 11:37 UTC, AyanoHara commented on RandomChoiceApp/Controller/SettingViewController.swift
> +class SettingViewController: UIViewController, UINavigationBarDelegate, UITableViewDataSource, UITableViewDelegate {
やはりチーム単位で制約を設けるのが一般的なのですね！

ちなみになんですが、現在このプロジェクトのコーディングルールとして自作メソッドをextensionとして分けるようにしているのですが一般的に自作メソッドはextesionに分ける必要はあるのでしょうか？

2020-12-07 14:45 UTC, fuchi0741 commented on RandomChoiceApp/Controller/SettingViewController.swift
> +        case 0:
enumの理解自分も深まりましたmm

2020-12-07 14:47 UTC, fuchi0741 commented on RandomChoiceApp/View/Cells/SettingTableViewCell.swift
> +    @IBOutlet weak var settingTitleLabel: UILabel!
おおdidSetはそう使用すればいいのかmm
didsetとかgetとかコンピューテッドあたりの整理ができていないので学習しますmm

2020-12-08 02:15 UTC, yamataku29 commented on RandomChoiceApp/Controller/SettingViewController.swift
> +class SettingViewController: UIViewController, UINavigationBarDelegate, UITableViewDataSource, UITableViewDelegate {
> ちなみになんですが、現在このプロジェクトのコーディングルールとして自作メソッドをextensionとして分けるようにしているのですが一般的に自作メソッドはextesionに分ける必要はあるのでしょうか？

これはケースバイケースですね💡
ここでいう「自作メソッドをextensionとして分ける」というのは、今回の様なクラスのブロックを分けるという意味なのか、それともプリミティブな型(StringやIntなど)のExtensionとしてメソッドやプロパティを追加するという意味なのか、どちらでしょうか？👀

2020-12-08 02:18 UTC, yamataku29 commented on RandomChoiceApp/Controller/SettingViewController.swift
> +
`else { return }`を追加したことと、`default: break`を削除したことは直接的な因果関係はありません💁‍♂️
switch文は通常、Optionalな値を評価する際には必ず`default`ケースが必要になります。
もしくは、`case`の分岐定義で全てのケースを網羅していない場合には`default`ケースを定義してあげないとコンパイルエラーになるのですね。

恐らく以前のコードでは、上記のいずれかに該当していたものと思われますね😌

2020-12-08 02:20 UTC, yamataku29 approved these changes
見ましたー！
よいと思います🙆‍♂️🎉

2020-12-09 13:05 UTC, AyanoHara commented on RandomChoiceApp/Controller/SettingViewController.swift
> +
なるほど、直接的な因果関係はないのですね。
以前のコードでは`SettingCategoryList`を活用せず、
```Swift
switch indexPath.row {
case0: 
case1: 
case2: 
}

```
としていたので、caseの分岐定義で全てのケースを網羅していなかった可能性が高いです。ありがとうございます🙇‍♀️

2020-12-09 13:06 UTC, AyanoHara commented on RandomChoiceApp/Controller/SettingViewController.swift
> +class SettingViewController: UIViewController, UINavigationBarDelegate, UITableViewDataSource, UITableViewDelegate {
今回と同様にクラスのブロックを分けるという意味でextensionを使用していました。

2020-12-09 13:24 UTC, merged